services:
  frankenphp:
    ports: !override
      - ${HTTP_PORT:-80}:80
    volumes:
      - ./symfony/docker/caddy/Caddyfile.uat:/etc/caddy/Caddyfile
      - './symfony/public/media:/app/public/media'
      - './symfony/public/files:/app/public/files'
    networks:
      - pdvir-network
  postgres:
    networks:
      - pdvir-network
  nominatim:
    networks:
      - pdvir-network
  qgis:
    networks:
      - pdvir-network
  osm2pgsql:
    networks:
      - pdvir-network

networks:
  pdvir-network:
    name: pdvir_network
    external: true
