export enum UserRoles {
    USER = 'ROLE_USER',
    ADMIN = 'ROLE_ADMIN',
    EDITOR_ACTORS = 'ROLE_EDITOR_ACTORS',
    ROLE_EDITOR_PROJECTS = 'ROLE_EDITOR_PROJECTS',
    ROLE_EDITOR_RESOURCES = 'ROLE_EDITOR_RESOURCES'
}