export enum UserRoles {
    USER = 'ROLE_USER',
    ADMIN = 'ROLE_ADMIN',
    EDITOR_ACTORS = 'ROLE_EDITOR_ACTORS',
    EDITOR_PROJECTS = 'ROLE_EDITOR_PROJECTS',
    EDITOR_RESOURCES = 'ROLE_EDITOR_RESOURCES',
    EDITOR_DATA = 'ROLE_EDITOR_DATA'
}