export enum AdministrationPanels {
  MEMBERS = 'MEMBERS',
  CONTENT = 'CONTENT',
  CONTENT_ACTORS = 'CONTENT_ACTORS',
  CONTENT_PROJECTS = 'CONTENT_PROJECTS',
  CONTENT_RESOURCES = 'CONTENT_RESOURCES',
  MAPS = 'MAPS',
  MAP_ATLAS = 'MAP_ATLAS',
  MAP_QGIS_PROJECT = 'MAP_QGIS_PROJECT',
  COMMENTS = 'COMMENTS'
}
