services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    App\Services\Serializer\:
        resource: '../../../src/Services/Serializer/'
    
    'App\Services\Serializer\UserContextBuilder':
        decorates: 'api_platform.serializer.context_builder'
        arguments: [ '@App\Services\Serializer\UserContextBuilder.inner' ]
        autoconfigure: false